### ISSUE TITLE
Adding spaces support

### ISSUE THREAD

**Issue by moenad** [mjolnirapp/mjolnir#523]
I used Amethyst before, it had some issues but it was possible to move windows between spaces.

I checked the source code, he made a small framework called Silica and you can check what he's doing here: 
https://github.com/ianyh/Silica/blob/master/Silica/SIWindow.m#L189

Basically he's emulating the mouse move, at least it works. Why not add it in both cases?

I'm not sure if you discussed this before, I'm just pointing out.

**Comment by hhsnopek** [comment]
So is there a package that allows us to move windows between spaces & switch us to that space? I've gotten lost on the thread here.
