### ISSUE TITLE
check for enabled accessibility on each start 

### ISSUE THREAD

**Issue by muescha** [mjolnirapp/mjolnir#539]
since `Disable and re-enable accessibility.` solves many problems. 

why not check on every restart if this option is activated and show a hint how to solve this?

**Comment by cmsj** [comment]
FWIW, we do this in Hammerspoon, you can just edit line 46 of MJAppDelegate.m to:

    if (MJFirstRunForCurrentVersion() || !MJAccessibilityIsEnabled())

**Comment by asmagill** [comment]
If you don't want to recompile Mjolnir and don't want to switch to Hammerspoon (there are some syntax changes to the functions and most of the Mjolnir modules people are currently putting out will require some tweaks, though many do end up being merged into Hammerspoon as they mature), you can use mjolnir._asm.hydra, available via luarocks, and add the following to your init.lua to get Hydra's original behavior of prompting you with a notification if it changed:

	require("mjolnir._asm.hydra").check_accessibility(true)
