### ISSUE TITLE
Open a file

### ISSUE THREAD

**Issue by andrewmc2** [mjolnirapp/mjolnir#541]
I have looking through the documentation on Dash, and I couldn't seem to find a way to open a particular file. For example, I'd like to open a .html file in Sublime (which is the default application to open this type of file). Is there a way to open particular files in an application with any module in Mjolnir/Lua?

**Comment by cmsj** [comment]
indirectly, you can use os.execute() to call out to /usr/bin/open, which has suitable arguments for opening a file with a particular application.
