### ISSUE TITLE
Upgrade to Lua 5.3

### ISSUE THREAD

**Issue by sdegutis** [mjolnirapp/mjolnir#570]
Lua 5.2 isn't official discontinued, but 5.3 has been out for a few years now, and Homebrew took 5.2 out of its main formula repository. So the path of least friction is to use Lua 5.3 moving forward.

**Comment by kwrobert** [comment]
I would really appreciate this upgrade. I spent quite awhile today trying to work around the lack of lua 5.3 support, but it ended up being too much trouble to manage a homebrew installation of lua 5.3 and a manually compiled installation of 5.2 so I gave up. I got things to work briefly, but as soon as I installed a module with a compiled C# extension things got difficult. Maybe it's my lack of understanding about the tooling around lua, but it would certainly make my life a whole lot easier if I could `brew install lua luarocks && brew cask install mjolnir` and be done with it. 

I think mjolnir seems really cool, so this wall I'm hitting is a bit of a bummer. I would appreciate any help on getting things running while I wait for 5.3 support!@

**Comment by andypearson** [comment]
I have just stupidly run `brew update` whilst trying to fix a thing and now my beloved Mjolnir is broken with this error :'(

**Comment by rileyjshaw** [comment]
We could also [create a 5.2 tap](https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md#how-to-create-and-maintain-a-tap) as recommended in https://github.com/Homebrew/homebrew-core/issues/24409#issuecomment-367572888?

**Comment by opsroller** [comment]
Adding support for LUA as a Framework dependency, with automated builds.

**Comment by sdegutis** [comment]
Closing as I'm no longer leading this repo. Feel free to open a new issue that includes both tasks.

**Comment by opsroller** [comment]
Moved to https://github.com/orgs/mjolnirapp/projects/1#card-21043765
