### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by jbenet** [mjolnirapp/mjolnir#571]
Please consider cutting another release. last release was in 2014, and there's 30+ commits on master since.

**Comment by sdegutis** [comment]
This is a good idea, pinging @opsroller.

**Comment by opsroller** [comment]
We’re going to bring continuous integration to the project very soon that will enable more continuous releases. Stay tuned.

**Comment by opsroller** [comment]
New version available with Lua 5.3.5 support and the Application is now signed for distribution.
