### ISSUE TITLE
Upgrade to LUA 5.3

### ISSUE THREAD

**Issue by opsroller** [mjolnirapp/mjolnir#574]

**Comment by rileyjshaw** [comment]
AAAH OMG! I'm so excited to see this – I didn't realize you made the upgrade. Thank you for all the time and effort that went into this.

Should we update the README, since it still references 5.2?

**Comment by opsroller** [comment]
Yeah, toss a pull request my way. If there’s anything else you see missing let me know.

**Comment by rileyjshaw** [comment]
On it.
